name = "Touhou Carlu Chronicles"
author = "TCS-Team"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d9efe39274ee3ab8322f694b0c0637f6216e7d44136675835b5ef6a6ed20ec0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
