name = "Touhou Carlu Chronicles"
author = "TCS-Team"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0a42c432902de7514681b08104b6904d6a57a65826903664af59f6ddeda72a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
